spring:
    profiles:
        active: dev
    servlet:
        multipart:
            max-file-size: 50MB
    application:
        name: FileStorageApp

server:
    servlet:
        context-path: /api/v1/
    port: 8090
